import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import vm from 'node:vm';
const read=f=>readFileSync(new URL(`../${f}`,import.meta.url),'utf8');
const manifest=JSON.parse(read('catalog-batch-manifest.json'));
const files=[...new Set(manifest.batches.flatMap(x=>x.files||[]))];
const ctx=vm.createContext({console});
for(const f of ['catalog-providers.js','catalog-adapters.js',...files,'catalog-fixtures.js','catalog.js'])vm.runInContext(read(f),ctx,{filename:f});
const c=ctx.FISH_TARGET_CATALOG,brs=c.list({maker:'JACKALL',series:'26 BRS'}).filter(x=>x.source.source_type==='manufacturer_official'),revoltage=c.list({maker:'JACKALL',series:'REVOLTAGE'}).filter(x=>x.source.source_type==='manufacturer_official');

test('JACKALL 26 BRS keeps all eleven official research rows production-blocked',()=>{const batch=manifest.batches.find(x=>x.id==='jackall-brs-2026');assert.ok(batch);assert.equal(batch.expected_rows,11);assert.equal(brs.length,11);assert.ok(c.makers.includes('JACKALL'));assert.equal(c.validateCatalog(c.products).length,0);assert.ok(brs.every(x=>x.category==='rod'&&x.status==='unknown'));assert.ok(brs.every(x=>x.source.source_provider==='jackall-official-research'&&x.source.license_status==='restricted'&&!c.productionEligible(x)));const jan=brs.map(x=>x.identifiers.jan);assert.equal(jan.length,11);assert.equal(new Set(jan).size,11);assert.ok(jan.every(x=>/^\d{13}$/.test(x)))});

test('26 BRS split PLUG and JIG limits never collapse into one fabricated generic lure range',()=>{const p=brs.find(x=>x.model==='BRS-S98L/M-SJ');assert.ok(p);assert.equal(p.specs.power,'L');assert.equal(p.specs.power_raw,'LIGHT');assert.equal(p.specs.lure_weight_raw,'PLUG MAX40g / JIG MAX50g');assert.equal(p.specs.lure_min_g,null);assert.equal(p.specs.lure_max_g,null);assert.equal(p.specs.jig_max_g,50);assert.equal(p.specs.line_pe_max,2.5);assert.equal(p.identifiers.jan,'4525807337280');assert.equal(c.ownedSnapshot(p,{id:'jackall-split'}).maxLure,null)});

test('26 BRS compound power remains raw instead of being forced into one canonical class',()=>{const p=brs.find(x=>x.model==='BRS-S100ML/MH-SJ');assert.ok(p);assert.equal(p.specs.power,'');assert.equal(p.specs.power_raw,'MEDIUM LIGHT / MEDIUM HEAVY');assert.equal(p.specs.lure_weight_raw,'PLUG MAX50g / JIG MAX70g');assert.equal(p.specs.lure_max_g,null);assert.equal(p.specs.jig_max_g,70)});

test('26 BRS preserves EGI and RIG units without inventing gram conversions',()=>{const egi=brs.find(x=>x.model==='BRS-S84ML'),rig=brs.find(x=>x.model==='BRS-S56SUL-LG');assert.ok(egi&&rig);assert.equal(egi.specs.lure_max_g,25);assert.equal(egi.specs.lure_weight_raw,'LURE MAX25g / EGI MAX #3.5');assert.equal(rig.specs.power,'');assert.equal(rig.specs.power_raw,'SUPER ULTRA LIGHT');assert.equal(rig.specs.lure_weight_raw,'RIG MAX 3g');assert.equal(rig.specs.lure_min_g,null);assert.equal(rig.specs.lure_max_g,null);assert.equal(rig.specs.line_pe_max,0.4)});

test('JACKALL REVOLTAGE keeps all twenty-seven official rows with no fabricated JAN',()=>{const batch=manifest.batches.find(x=>x.id==='jackall-revoltage-2026');assert.ok(batch);assert.equal(batch.expected_rows,27);assert.equal(revoltage.length,27);assert.equal(c.validateCatalog(c.products).length,0);assert.ok(revoltage.every(x=>x.category==='rod'&&x.status==='unknown'));assert.ok(revoltage.every(x=>x.source.source_provider==='jackall-official-research'&&x.source.license_status==='restricted'&&!c.productionEligible(x)));assert.ok(revoltage.every(x=>!x.identifiers?.jan))});

test('REVOLTAGE raw-only ounce ranges are never converted to grams',()=>{const mh=revoltage.find(x=>x.model==='RVⅡ-C70MH-R'),hp=revoltage.find(x=>x.model==='RVⅡ-C70H+R'),xul=revoltage.find(x=>x.model==='RVⅡ-S56XUL/L-ST');assert.ok(mh&&hp&&xul);assert.equal(mh.specs.lure_weight_raw,'1/4-1oz');assert.equal(mh.specs.lure_min_g,null);assert.equal(mh.specs.lure_max_g,null);assert.equal(hp.specs.lure_weight_raw,'3/8-1•1/2oz');assert.equal(hp.specs.lure_min_g,null);assert.equal(hp.specs.lure_max_g,null);assert.equal(hp.specs.line_pe_max,5);assert.equal(xul.specs.lure_weight_raw,'1/64-3/16oz');assert.equal(xul.specs.lure_min_g,null);assert.equal(xul.specs.lure_max_g,null);assert.equal(xul.specs.power,'');assert.equal(xul.specs.power_raw,'EXTRA ULTRA LIGHT')});

test('REVOLTAGE unitless lure figures stay raw while metric-only length may normalize internally',()=>{const s65=revoltage.find(x=>x.model==='RVⅡ-S65L'),s67=revoltage.find(x=>x.model==='RVⅡ-S67ML');assert.ok(s65&&s67);assert.equal(s65.specs.lure_weight_raw,'0.9-7');assert.equal(s65.specs.lure_min_g,null);assert.equal(s65.specs.lure_max_g,null);assert.equal(s65.specs.line_pe_max,1);assert.equal(s67.specs.length_m,2.01);assert.ok(Math.abs(s67.specs.length_ft-6.594)<0.001);assert.equal(s67.specs.length_raw,'2.01m');assert.equal(s67.specs.lure_weight_raw,'1.8-14');assert.equal(s67.specs.lure_min_g,null);assert.equal(s67.specs.lure_max_g,null);assert.equal(s67.specs.line_pe_max,1.5)});

test('REVOLTAGE uses manufacturer-supplied gram values only when explicitly provided',()=>{const p=revoltage.find(x=>x.model==='RVⅡ-C67MH+');assert.ok(p);assert.equal(p.specs.power,'');assert.equal(p.specs.power_raw,'MEDIUM HEAVY PLUS');assert.equal(p.specs.lure_weight_raw,'3/8-2oz (10.5-56g)');assert.equal(p.specs.lure_min_g,10.5);assert.equal(p.specs.lure_max_g,56);assert.equal(p.specs.line_pe_max,5);assert.equal(c.ownedSnapshot(p,{id:'jackall-rev'}).maxLure,56)});
